# Generated by Django 6.0.2 on 2026-02-21 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('current_load', models.IntegerField(default=0)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessunit')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_guid', models.UUIDField(default=uuid.uuid4)),
                ('gender', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('segment', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manager')),
            ],
        ),
    ]
