# Generated by Django 6.0.2 on 2026-02-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_manager',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='summary',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manager')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='api.ticket')),
            ],
        ),
    ]
