# Generated by Django 5.2.5 on 2026-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ticket_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
