# Generated by Django 6.0.2 on 2026-02-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_is_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_skipped',
        ),
    ]
